### PR TITLE
Span tag with href attr is invalid, strip it

### PR DESCRIPTION
**Pull request by zharikovpro**
I used [html5validator](https://github.com/svenkreiss/html5validator) to check generated html. When using span_currents=true option, plugin leaves href attr in them. In that case validator will show error 'attribute href not allowed on element span'. This PR fixes it.

### CODE REVIEW

**Comment by zharikovpro** [comment]
Sadly, I dont understand the meaning of the "Span must have relative href attr" test which fails after my commit. Could you explain how to merge it correctly?

**Comment by zharikovpro** [comment]
Guess that it's a feature for test suite. For example, href attr can be renamed into data-href attr to preserve valid markup and ability to pass tests? Also this info can be useful for client-side scripts (just in case).

**Comment by chivorotkiv** [comment]
Hi @zharikovpro

> this info can be useful for client-side scripts 

You're right I've left `href` attribute because it could be useful in frontend scripts.

> For example, href attr can be renamed into data-href attr to preserve valid markup and ability to pass tests?

That's a good idea. Could you please do following:

* rename `href` to `data-href` instead of deleting and fix the test
* merge last master to your branch
* set 1.0.3 version and update CHANGELOG.md

That would be really helpful if you could do this.

**Comment by zharikovpro** [comment]
Okay, will post update later today.

**Comment by zharikovpro** [comment]
Done. Fork was based on latest master and I'm not sure if I can merge anything else (or dont know how). Please check if anything else can be done from my side. All tests are green now.

**Comment by chivorotkiv** [comment]
@zharikovpro 

Could you please do following at your local repo:

```
git remote add -f evoja https://github.com/evoja/metalsmith-prefixoid.git
git merge evoja/master
```

Then fix conflict in two files.
Commit using command `git commit -a`
It should open a text editor with prepared message about merge and conflict. Just save and quit. 

Then push to origin (zharikovpro/metalsmith-prefixoid).

**Comment by zharikovpro** [comment]
Great, it worked, thank you.

**Pull request merged**
